(define (problem hanoi-2)
(:domain hanoi)
(:objects peg1 peg2 peg3 d1 d2 )
(:init
    (disc d1)
    (disc d2)
    (peg peg1)
    (peg peg2)
    (peg peg3)
    (emptyPince)
    (smaller peg1 d1)
    (smaller peg1 d2)
    (smaller peg2 d1)
    (smaller peg2 d2)
    (smaller peg3 d1)
    (smaller peg3 d2)
    (smaller d2 d1)
    (vide peg2)
    (vide peg3)
    (clear d1)
    (on d2 peg1)
    (on d1 d2)
)
(:goal
    (and 
    (on d2 peg3)
    (on d1 d2)
    )
)
)